name: Publish releases

on:
  release:
    types: [published]

env:
  PYTHON_VERSION: "3.11"
  BASE_IMAGE_VERSION_STABLE: "1.1.2"
  BASE_IMAGE_VERSION_BETA: "1.1.2"

jobs:
  build-artifact:
    name: Builds python artifact uploads to Github Artifact store
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.tag }}
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Get tag
        id: vars
        run: >-
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Validate version number
        run: >-
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            if ! [[ "${{ steps.vars.outputs.tag }}" =~ "b" || "${{ steps.vars.outputs.tag }}" =~ "rc" ]]; then
            echo "Pre-release: Tag is missing beta suffix (${{ steps.vars.outputs.tag }})"
              exit 1
            fi
          else
            if [[ "${{ steps.vars.outputs.tag }}" =~ "b" || "${{ steps.vars.outputs.tag }}" =~ "rc" ]]; then
              echo "Release: Tag must not have a beta (or rc) suffix (${{ steps.vars.outputs.tag }})"
              exit 1
            fi
          fi
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install build
        run: >-
          pip install build tomli tomli-w
      - name: Set Python project version from tag
        shell: python
        run: |-
          import tomli
          import tomli_w

          with open("pyproject.toml", "rb") as f:
            pyproject = tomli.load(f)

          pyproject["project"]["version"] = "${{ steps.vars.outputs.tag }}"

          with open("pyproject.toml", "wb") as f:
            tomli_w.dump(pyproject, f)
      - name: Build python package
        run: >-
          python3 -m build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    name: Publish release to PyPI (stable releases only)
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:
      - name: Retrieve release distributions
        if: ${{ github.event.release.prerelease == false }}
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish release to PyPI
        if: ${{ github.event.release.prerelease == false }}
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

  build-and-push-container-image:
    name: Builds and pushes the Music Assistant Server container to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs:
      - build-artifact
      - pypi-publish
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Version number for tags
        id: tags
        shell: bash
        run: |-
          patch=${GITHUB_REF#refs/*/}
          echo "patch=${patch}" >> $GITHUB_OUTPUT
          echo "minor=${patch%.*}" >> $GITHUB_OUTPUT
          echo "major=${patch%.*.*}" >> $GITHUB_OUTPUT
      - name: Build and Push release
        uses: docker/build-push-action@v6.9.0
        if: ${{ github.event.release.prerelease == false }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          tags: |-
            ghcr.io/${{ github.repository_owner }}/server:${{ steps.tags.outputs.patch }},
            ghcr.io/${{ github.repository_owner }}/server:${{ steps.tags.outputs.minor }},
            ghcr.io/${{ github.repository_owner }}/server:${{ steps.tags.outputs.major }},
            ghcr.io/${{ github.repository_owner }}/server:stable,
            ghcr.io/${{ github.repository_owner }}/server:latest
          push: true
          build-args: |
            MASS_VERSION=${{ needs.build-artifact.outputs.version }}
            BASE_IMAGE_VERSION=${{ env.BASE_IMAGE_VERSION_STABLE }}
      - name: Build and Push pre-release
        uses: docker/build-push-action@v6.9.0
        if: ${{ github.event.release.prerelease == true }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          tags: |-
            ghcr.io/${{ github.repository_owner }}/server:${{ steps.tags.outputs.patch }},
            ghcr.io/${{ github.repository_owner }}/server:beta
          push: true
          build-args: |
            MASS_VERSION=${{ needs.build-artifact.outputs.version }}
            BASE_IMAGE_VERSION=${{ env.BASE_IMAGE_VERSION_BETA }}

  release-notes-update:
    name: Updates the release notes and changelog
    needs: [build-artifact, pypi-publish, build-and-push-container-image]
    runs-on: ubuntu-latest
    steps:
      - name: Update changelog and release notes including frontend notes
        uses: music-assistant/release-notes-merge-action@main
        with:
          github_token: ${{ secrets.PRIVILEGED_GITHUB_TOKEN }}
          release_tag: ${{ needs.build-artifact.outputs.version }}
          pre_release: ${{ github.event.release.prerelease }}

  addon-version-update:
    name: Updates the Addon repository with the new version
    needs:
      - build-artifact
      - pypi-publish
      - build-and-push-container-image
      - release-notes-update
    runs-on: ubuntu-latest
    steps:
      - name: Push new version number to addon config
        uses: music-assistant/addon-update-action@main
        with:
          github_token: ${{ secrets.PRIVILEGED_GITHUB_TOKEN }}
          new_server_version: ${{ needs.build-artifact.outputs.version }}
          pre_release: ${{ github.event.release.prerelease }}
